version: '3'
services:
  web:
    build: .
    ports:
     - "4000:4000"
    environment:
      - DEBUG_ERRORS="true"
      - CRONJOBS_ENABLED="false"
      - PROJECT_ARC_BUCKET="cryptomarker-prod"
      - SECRET_KEY_BASE="jfidasojf9j32jafm34i923uufeaijfdiosajf932u98fjdsajfdsoiaoj"
      - DATABASE_MYSQL_HOSTNAME="mariadb"
      - DATABASE_MYSQL_PORT="3306"
      - DATABASE_MYSQL_USERNAME="root"
      - DATABASE_MYSQL_PASSWORD=""
      - DATABASE_MYSQL_DATABASE="cryptomarker_dev"
    depends_on:
      - mariadb
  mariadb:
    image: 'bitnami/mariadb:latest'
    healthcheck:
      # test: "/usr/bin/mysql --host=127.0.0.1 --user=root -p --execute \"SHOW DATABASES;\""
      # test: "/usr/local/mysql/bin/mysql --user=foo --password=foo --execute \"SHOW DATABASES;\""
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "3306"
